services:
  postgres:
    image: postgres:17
    container_name: postgres
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak
    environment:
      KC_HTTP_PORT: 8180
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_URL_HOST: localhost
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      DEBUG: true
    command: "start-dev --import-realm --verbose"
    volumes:
      - ./src/main/resources/sudoku-realm.json:/opt/keycloak/data/import/sudoku-realm.json
    network_mode: host
    depends_on:
      - postgres

  backend:
    image: sudoku/backend:latest
    container_name: backend
    network_mode: host
    depends_on:
      - postgres
      - keycloak

